### ISSUE TITLE
JUICY-00001: Code standardization

### ISSUE THREAD

**Issue by miltonio94** [dmoa/juice#1]
The code needs standardising.
1. Lint the code
2. consistent use of preprocessor
3. removal of `#pragma once` in favor of `#ifndef`

**Comment by miltonio94** [comment]
styel guide has been applied @dmoa check the new style and see if you're okay with it as well. studio code should pick up the formatting settings automagically and if you have format on save turned on it should pick it up automagically

**Comment by miltonio94** [comment]
removed all pragma once from the engine. has been replaced by ifndef

**Comment by miltonio94** [comment]
includes consistent now

**Comment by miltonio94** [comment]
fixes are on branch Juicy-00001

**Comment by dmoa** [comment]
All issues fixed.
