### ISSUE TITLE
JUICY-00002: Engine as its own separate component 

### ISSUE THREAD

**Issue by miltonio94** [dmoa/juice#2]
I think we would benefit greatly from making the engine its own repo. This would help greatly with maintainability and would reduce the pollution of our project. 

If we decide to go ahead with this (my vote is yes) we have to make another decision, do we keep it here as a sub repo or do we leave it to the user of the code base to take care of linking it themselves and dealing with the config themselves

**Comment by dmoa** [comment]
Done
