### ISSUE TITLE
JUICY-00004: Include dir with engine not being picked up by auto completion engine

### ISSUE THREAD

**Issue by miltonio94** [dmoa/juice#7]
Look into clang complete to solve this

**Comment by miltonio94** [comment]
I have fixed this for my emacs config. @dmoa have you been having the same issue with vs code? If you have those this new file I've added (requires ccls installed) fix the issue for you?

**Comment by dmoa** [comment]
I don't use autocomplete, so all good to close this.

**Comment by miltonio94** [comment]
I need it though 😅

**Comment by miltonio94** [comment]
also i did a dumb dumb and tackled the linux bug here

**Comment by miltonio94** [comment]
I've opened it again. Will merge the PR and than close 5 as well
